linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - unused
    - misspell

linters-settings:
  govet:
    shadow: true

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
